company:
  class: sfPropelORMRouteCollection
  options:
    model:                Company
    module:               company
    prefix_path:          /company
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: booking, action: index }

booking_copy:
  url:   /clona-prenotazione
  param: { module: booking, action: copy }

booking:
    url:   /gestione-prenotazioni
    param: { module: booking, action: index }

company:
    url:   /dati-aziendali
    param: { module: company, action: index }

company_create:
    url:   /company-create
    param: { module: company, action: create }

company_update:
    url:   /company-update
    param: { module: company, action: update }

vehicle_type:
    url:   /categorie-mezzi
    param: { module: vehicleType, action: index }

vehicle_type_new:
    url:   /nuova-categoria-mezzi
    param: { module: vehicleType, action: new }

vehicle_type_edit:
    url:   /modifica-categoria-mezzi/:id
    param: { module: vehicleType, action: new }
    requirements:
      id: \d+

vehicle_type_create:
    url:   /crea-categoria-mezzi
    param: { module: vehicleType, action: create }

vehicle_type_update:
    url:   /aggiorna-categoria-mezzi
    param: { module: vehicleType, action: update }

vehicle:
    url:   /mezzi
    param: { module: vehicle, action: index }

vehicle_new:
    url:   /nuovo-mezzo
    param: { module: vehicle, action: new }

vehicle_edit:
    url:   /modifica-mezzo/:id
    param: { module: vehicle, action: new }
    requirements:
      id: \d+

vehicle_create:
    url:   /crea-mezzo
    param: { module: vehicle, action: create }

vehicle_update:
    url:   /aggiorna-mezzo
    param: { module: vehicle, action: update }


customer:
    url:   /clienti
    param: { module: customer, action: index }

customer_new:
    url:   /nuovo-cliente
    param: { module: customer, action: new }

customer_edit:
    url:   /modifica-cliente/:id
    param: { module: customer, action: new }
    requirements:
      id: \d+

customer_create:
    url:   /crea-cliente
    param: { module: customer, action: create }

customer_update:
    url:   /aggiorna-cliente
    param: { module: customer, action: update }

users:
  url:   /gestione-utenti
  param: { module: users, action: index }

user_new:
    url:   /nuovo-utente
    param: { module: users, action: new }

user_edit:
    url:   /modifica-utente/:id
    param: { module: users, action: new }
    requirements:
      id: \d+

user_create:
    url:   /crea-utente
    param: { module: users, action: create }

user_update:
    url:   /aggiorna-utente
    param: { module: users, action: update }


locality:
    url:   /localita
    param: { module: locality, action: index }

locality_new:
    url:   /nuova-localita
    param: { module: locality, action: new }

locality_edit:
    url:   /modifica-localita/:id
    param: { module: locality, action: new }
    requirements:
      id: \d+

locality_create:
    url:   /crea-localita
    param: { module: locality, action: create }

locality_update:
    url:   /aggiorna-localita
    param: { module: locality, action: update }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
