# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Benvenuti in Transfer
    #description:  symfony project
    #keywords:     symfony, project
    language:     it
    #robots:       index, follow

  stylesheets:
      - main.css
      - jq-theme/jquery-ui-1.8.16.custom.css

  javascripts:
      - jquery.min.js
      - bootstrap.js
      - bootbox.min.js
      - jq-theme/jquery-ui-1.8.16.custom.min.js

  has_layout:     true
  layout:         layout
