<?php



/**
 * This class defines the structure of the 'customer_rate_extra' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sat Dec  6 11:52:06 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class CustomerRateExtraTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.CustomerRateExtraTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('customer_rate_extra');
        $this->setPhpName('CustomerRateExtra');
        $this->setClassname('CustomerRateExtra');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(false);
        // columns
        $this->addForeignPrimaryKey('CUSTOMER_ID', 'CustomerId', 'INTEGER' , 'sf_guard_user_profile', 'ID', true, null, null);
        $this->addForeignPrimaryKey('RATE_EXTRA_ID', 'RateExtraId', 'INTEGER' , 'rate_extra', 'ID', true, null, null);
        $this->addColumn('VALUE', 'Value', 'DECIMAL', true, 10, 0);
        $this->addColumn('TYPOLOGY', 'Typology', 'ENUM', false, null, null);
        $this->getColumn('TYPOLOGY', false)->setValueSet(array (
  0 => 'percentuale',
  1 => 'addizionale',
));
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Customer', 'Customer', RelationMap::MANY_TO_ONE, array('customer_id' => 'id', ), null, null);
        $this->addRelation('RateExtra', 'RateExtra', RelationMap::MANY_TO_ONE, array('rate_extra_id' => 'id', ), null, null);
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
        );
    } // getBehaviors()

} // CustomerRateExtraTableMap
