<?php


/**
 * Base static class for performing query and update operations on the 'booking_version' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Nov 17 17:31:38 2014
 *
 * @package propel.generator.lib.model.om
 */
abstract class BaseBookingVersionPeer
{

    /** the default database name for this class */
    const DATABASE_NAME = 'propel';

    /** the table name for this class */
    const TABLE_NAME = 'booking_version';

    /** the related Propel class for this table */
    const OM_CLASS = 'BookingVersion';

    /** the related TableMap class for this table */
    const TM_CLASS = 'BookingVersionTableMap';

    /** The total number of columns. */
    const NUM_COLUMNS = 21;

    /** The number of lazy-loaded columns. */
    const NUM_LAZY_LOAD_COLUMNS = 0;

    /** The number of columns to hydrate (NUM_COLUMNS - NUM_LAZY_LOAD_COLUMNS) */
    const NUM_HYDRATE_COLUMNS = 21;

    /** the column name for the ID field */
    const ID = 'booking_version.ID';

    /** the column name for the BOOKING_DATE field */
    const BOOKING_DATE = 'booking_version.BOOKING_DATE';

    /** the column name for the YEAR field */
    const YEAR = 'booking_version.YEAR';

    /** the column name for the NUMBER field */
    const NUMBER = 'booking_version.NUMBER';

    /** the column name for the ADULT field */
    const ADULT = 'booking_version.ADULT';

    /** the column name for the REDUCED field */
    const REDUCED = 'booking_version.REDUCED';

    /** the column name for the CHILD field */
    const CHILD = 'booking_version.CHILD';

    /** the column name for the CONTACT field */
    const CONTACT = 'booking_version.CONTACT';

    /** the column name for the RIF_FILE field */
    const RIF_FILE = 'booking_version.RIF_FILE';

    /** the column name for the CUSTOMER_ID field */
    const CUSTOMER_ID = 'booking_version.CUSTOMER_ID';

    /** the column name for the VEHICLE_TYPE_ID field */
    const VEHICLE_TYPE_ID = 'booking_version.VEHICLE_TYPE_ID';

    /** the column name for the IS_CONFIRMED field */
    const IS_CONFIRMED = 'booking_version.IS_CONFIRMED';

    /** the column name for the CREATED_AT field */
    const CREATED_AT = 'booking_version.CREATED_AT';

    /** the column name for the UPDATED_AT field */
    const UPDATED_AT = 'booking_version.UPDATED_AT';

    /** the column name for the VERSION field */
    const VERSION = 'booking_version.VERSION';

    /** the column name for the VERSION_CREATED_AT field */
    const VERSION_CREATED_AT = 'booking_version.VERSION_CREATED_AT';

    /** the column name for the VERSION_CREATED_BY field */
    const VERSION_CREATED_BY = 'booking_version.VERSION_CREATED_BY';

    /** the column name for the ARRIVAL_IDS field */
    const ARRIVAL_IDS = 'booking_version.ARRIVAL_IDS';

    /** the column name for the ARRIVAL_VERSIONS field */
    const ARRIVAL_VERSIONS = 'booking_version.ARRIVAL_VERSIONS';

    /** the column name for the DEPARTURE_IDS field */
    const DEPARTURE_IDS = 'booking_version.DEPARTURE_IDS';

    /** the column name for the DEPARTURE_VERSIONS field */
    const DEPARTURE_VERSIONS = 'booking_version.DEPARTURE_VERSIONS';

    /** The default string format for model objects of the related table **/
    const DEFAULT_STRING_FORMAT = 'YAML';

    /**
     * An identiy map to hold any loaded instances of BookingVersion objects.
     * This must be public so that other peer classes can access this when hydrating from JOIN
     * queries.
     * @var        array BookingVersion[]
     */
    public static $instances = array();


    /**
     * holds an array of fieldnames
     *
     * first dimension keys are the type constants
     * e.g. BookingVersionPeer::$fieldNames[BookingVersionPeer::TYPE_PHPNAME][0] = 'Id'
     */
    protected static $fieldNames = array (
        BasePeer::TYPE_PHPNAME => array ('Id', 'BookingDate', 'Year', 'Number', 'Adult', 'Reduced', 'Child', 'Contact', 'RifFile', 'CustomerId', 'VehicleTypeId', 'IsConfirmed', 'CreatedAt', 'UpdatedAt', 'Version', 'VersionCreatedAt', 'VersionCreatedBy', 'ArrivalIds', 'ArrivalVersions', 'DepartureIds', 'DepartureVersions', ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'bookingDate', 'year', 'number', 'adult', 'reduced', 'child', 'contact', 'rifFile', 'customerId', 'vehicleTypeId', 'isConfirmed', 'createdAt', 'updatedAt', 'version', 'versionCreatedAt', 'versionCreatedBy', 'arrivalIds', 'arrivalVersions', 'departureIds', 'departureVersions', ),
        BasePeer::TYPE_COLNAME => array (BookingVersionPeer::ID, BookingVersionPeer::BOOKING_DATE, BookingVersionPeer::YEAR, BookingVersionPeer::NUMBER, BookingVersionPeer::ADULT, BookingVersionPeer::REDUCED, BookingVersionPeer::CHILD, BookingVersionPeer::CONTACT, BookingVersionPeer::RIF_FILE, BookingVersionPeer::CUSTOMER_ID, BookingVersionPeer::VEHICLE_TYPE_ID, BookingVersionPeer::IS_CONFIRMED, BookingVersionPeer::CREATED_AT, BookingVersionPeer::UPDATED_AT, BookingVersionPeer::VERSION, BookingVersionPeer::VERSION_CREATED_AT, BookingVersionPeer::VERSION_CREATED_BY, BookingVersionPeer::ARRIVAL_IDS, BookingVersionPeer::ARRIVAL_VERSIONS, BookingVersionPeer::DEPARTURE_IDS, BookingVersionPeer::DEPARTURE_VERSIONS, ),
        BasePeer::TYPE_RAW_COLNAME => array ('ID', 'BOOKING_DATE', 'YEAR', 'NUMBER', 'ADULT', 'REDUCED', 'CHILD', 'CONTACT', 'RIF_FILE', 'CUSTOMER_ID', 'VEHICLE_TYPE_ID', 'IS_CONFIRMED', 'CREATED_AT', 'UPDATED_AT', 'VERSION', 'VERSION_CREATED_AT', 'VERSION_CREATED_BY', 'ARRIVAL_IDS', 'ARRIVAL_VERSIONS', 'DEPARTURE_IDS', 'DEPARTURE_VERSIONS', ),
        BasePeer::TYPE_FIELDNAME => array ('id', 'booking_date', 'year', 'number', 'adult', 'reduced', 'child', 'contact', 'rif_file', 'customer_id', 'vehicle_type_id', 'is_confirmed', 'created_at', 'updated_at', 'version', 'version_created_at', 'version_created_by', 'arrival_ids', 'arrival_versions', 'departure_ids', 'departure_versions', ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, )
    );

    /**
     * holds an array of keys for quick access to the fieldnames array
     *
     * first dimension keys are the type constants
     * e.g. BookingVersionPeer::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
     */
    protected static $fieldKeys = array (
        BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'BookingDate' => 1, 'Year' => 2, 'Number' => 3, 'Adult' => 4, 'Reduced' => 5, 'Child' => 6, 'Contact' => 7, 'RifFile' => 8, 'CustomerId' => 9, 'VehicleTypeId' => 10, 'IsConfirmed' => 11, 'CreatedAt' => 12, 'UpdatedAt' => 13, 'Version' => 14, 'VersionCreatedAt' => 15, 'VersionCreatedBy' => 16, 'ArrivalIds' => 17, 'ArrivalVersions' => 18, 'DepartureIds' => 19, 'DepartureVersions' => 20, ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'bookingDate' => 1, 'year' => 2, 'number' => 3, 'adult' => 4, 'reduced' => 5, 'child' => 6, 'contact' => 7, 'rifFile' => 8, 'customerId' => 9, 'vehicleTypeId' => 10, 'isConfirmed' => 11, 'createdAt' => 12, 'updatedAt' => 13, 'version' => 14, 'versionCreatedAt' => 15, 'versionCreatedBy' => 16, 'arrivalIds' => 17, 'arrivalVersions' => 18, 'departureIds' => 19, 'departureVersions' => 20, ),
        BasePeer::TYPE_COLNAME => array (BookingVersionPeer::ID => 0, BookingVersionPeer::BOOKING_DATE => 1, BookingVersionPeer::YEAR => 2, BookingVersionPeer::NUMBER => 3, BookingVersionPeer::ADULT => 4, BookingVersionPeer::REDUCED => 5, BookingVersionPeer::CHILD => 6, BookingVersionPeer::CONTACT => 7, BookingVersionPeer::RIF_FILE => 8, BookingVersionPeer::CUSTOMER_ID => 9, BookingVersionPeer::VEHICLE_TYPE_ID => 10, BookingVersionPeer::IS_CONFIRMED => 11, BookingVersionPeer::CREATED_AT => 12, BookingVersionPeer::UPDATED_AT => 13, BookingVersionPeer::VERSION => 14, BookingVersionPeer::VERSION_CREATED_AT => 15, BookingVersionPeer::VERSION_CREATED_BY => 16, BookingVersionPeer::ARRIVAL_IDS => 17, BookingVersionPeer::ARRIVAL_VERSIONS => 18, BookingVersionPeer::DEPARTURE_IDS => 19, BookingVersionPeer::DEPARTURE_VERSIONS => 20, ),
        BasePeer::TYPE_RAW_COLNAME => array ('ID' => 0, 'BOOKING_DATE' => 1, 'YEAR' => 2, 'NUMBER' => 3, 'ADULT' => 4, 'REDUCED' => 5, 'CHILD' => 6, 'CONTACT' => 7, 'RIF_FILE' => 8, 'CUSTOMER_ID' => 9, 'VEHICLE_TYPE_ID' => 10, 'IS_CONFIRMED' => 11, 'CREATED_AT' => 12, 'UPDATED_AT' => 13, 'VERSION' => 14, 'VERSION_CREATED_AT' => 15, 'VERSION_CREATED_BY' => 16, 'ARRIVAL_IDS' => 17, 'ARRIVAL_VERSIONS' => 18, 'DEPARTURE_IDS' => 19, 'DEPARTURE_VERSIONS' => 20, ),
        BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'booking_date' => 1, 'year' => 2, 'number' => 3, 'adult' => 4, 'reduced' => 5, 'child' => 6, 'contact' => 7, 'rif_file' => 8, 'customer_id' => 9, 'vehicle_type_id' => 10, 'is_confirmed' => 11, 'created_at' => 12, 'updated_at' => 13, 'version' => 14, 'version_created_at' => 15, 'version_created_by' => 16, 'arrival_ids' => 17, 'arrival_versions' => 18, 'departure_ids' => 19, 'departure_versions' => 20, ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, )
    );

    /**
     * Translates a fieldname to another type
     *
     * @param      string $name field name
     * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @param      string $toType   One of the class type constants
     * @return string          translated name of the field.
     * @throws PropelException - if the specified name could not be found in the fieldname mappings.
     */
    public static function translateFieldName($name, $fromType, $toType)
    {
        $toNames = BookingVersionPeer::getFieldNames($toType);
        $key = isset(BookingVersionPeer::$fieldKeys[$fromType][$name]) ? BookingVersionPeer::$fieldKeys[$fromType][$name] : null;
        if ($key === null) {
            throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(BookingVersionPeer::$fieldKeys[$fromType], true));
        }

        return $toNames[$key];
    }

    /**
     * Returns an array of field names.
     *
     * @param      string $type The type of fieldnames to return:
     *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @return array           A list of field names
     * @throws PropelException - if the type is not valid.
     */
    public static function getFieldNames($type = BasePeer::TYPE_PHPNAME)
    {
        if (!array_key_exists($type, BookingVersionPeer::$fieldNames)) {
            throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
        }

        return BookingVersionPeer::$fieldNames[$type];
    }

    /**
     * Convenience method which changes table.column to alias.column.
     *
     * Using this method you can maintain SQL abstraction while using column aliases.
     * <code>
     *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
     *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
     * </code>
     * @param      string $alias The alias for the current table.
     * @param      string $column The column name for current table. (i.e. BookingVersionPeer::COLUMN_NAME).
     * @return string
     */
    public static function alias($alias, $column)
    {
        return str_replace(BookingVersionPeer::TABLE_NAME.'.', $alias.'.', $column);
    }

    /**
     * Add all the columns needed to create a new object.
     *
     * Note: any columns that were marked with lazyLoad="true" in the
     * XML schema will not be added to the select list and only loaded
     * on demand.
     *
     * @param      Criteria $criteria object containing the columns to add.
     * @param      string   $alias    optional table alias
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function addSelectColumns(Criteria $criteria, $alias = null)
    {
        if (null === $alias) {
            $criteria->addSelectColumn(BookingVersionPeer::ID);
            $criteria->addSelectColumn(BookingVersionPeer::BOOKING_DATE);
            $criteria->addSelectColumn(BookingVersionPeer::YEAR);
            $criteria->addSelectColumn(BookingVersionPeer::NUMBER);
            $criteria->addSelectColumn(BookingVersionPeer::ADULT);
            $criteria->addSelectColumn(BookingVersionPeer::REDUCED);
            $criteria->addSelectColumn(BookingVersionPeer::CHILD);
            $criteria->addSelectColumn(BookingVersionPeer::CONTACT);
            $criteria->addSelectColumn(BookingVersionPeer::RIF_FILE);
            $criteria->addSelectColumn(BookingVersionPeer::CUSTOMER_ID);
            $criteria->addSelectColumn(BookingVersionPeer::VEHICLE_TYPE_ID);
            $criteria->addSelectColumn(BookingVersionPeer::IS_CONFIRMED);
            $criteria->addSelectColumn(BookingVersionPeer::CREATED_AT);
            $criteria->addSelectColumn(BookingVersionPeer::UPDATED_AT);
            $criteria->addSelectColumn(BookingVersionPeer::VERSION);
            $criteria->addSelectColumn(BookingVersionPeer::VERSION_CREATED_AT);
            $criteria->addSelectColumn(BookingVersionPeer::VERSION_CREATED_BY);
            $criteria->addSelectColumn(BookingVersionPeer::ARRIVAL_IDS);
            $criteria->addSelectColumn(BookingVersionPeer::ARRIVAL_VERSIONS);
            $criteria->addSelectColumn(BookingVersionPeer::DEPARTURE_IDS);
            $criteria->addSelectColumn(BookingVersionPeer::DEPARTURE_VERSIONS);
        } else {
            $criteria->addSelectColumn($alias . '.ID');
            $criteria->addSelectColumn($alias . '.BOOKING_DATE');
            $criteria->addSelectColumn($alias . '.YEAR');
            $criteria->addSelectColumn($alias . '.NUMBER');
            $criteria->addSelectColumn($alias . '.ADULT');
            $criteria->addSelectColumn($alias . '.REDUCED');
            $criteria->addSelectColumn($alias . '.CHILD');
            $criteria->addSelectColumn($alias . '.CONTACT');
            $criteria->addSelectColumn($alias . '.RIF_FILE');
            $criteria->addSelectColumn($alias . '.CUSTOMER_ID');
            $criteria->addSelectColumn($alias . '.VEHICLE_TYPE_ID');
            $criteria->addSelectColumn($alias . '.IS_CONFIRMED');
            $criteria->addSelectColumn($alias . '.CREATED_AT');
            $criteria->addSelectColumn($alias . '.UPDATED_AT');
            $criteria->addSelectColumn($alias . '.VERSION');
            $criteria->addSelectColumn($alias . '.VERSION_CREATED_AT');
            $criteria->addSelectColumn($alias . '.VERSION_CREATED_BY');
            $criteria->addSelectColumn($alias . '.ARRIVAL_IDS');
            $criteria->addSelectColumn($alias . '.ARRIVAL_VERSIONS');
            $criteria->addSelectColumn($alias . '.DEPARTURE_IDS');
            $criteria->addSelectColumn($alias . '.DEPARTURE_VERSIONS');
        }
    }

    /**
     * Returns the number of rows matching criteria.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @return int Number of matching rows.
     */
    public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
    {
        // we may modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(BookingVersionPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            BookingVersionPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
        $criteria->setDbName(BookingVersionPeer::DATABASE_NAME); // Set the correct dbName

        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseBookingVersionPeer', $criteria, $con);
        }

        // BasePeer returns a PDOStatement
        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }
    /**
     * Selects one object from the DB.
     *
     * @param      Criteria $criteria object used to create the SELECT statement.
     * @param      PropelPDO $con
     * @return                 BookingVersion
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
    {
        $critcopy = clone $criteria;
        $critcopy->setLimit(1);
        $objects = BookingVersionPeer::doSelect($critcopy, $con);
        if ($objects) {
            return $objects[0];
        }

        return null;
    }
    /**
     * Selects several row from the DB.
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con
     * @return array           Array of selected Objects
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelect(Criteria $criteria, PropelPDO $con = null)
    {
        return BookingVersionPeer::populateObjects(BookingVersionPeer::doSelectStmt($criteria, $con));
    }
    /**
     * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
     *
     * Use this method directly if you want to work with an executed statement durirectly (for example
     * to perform your own object hydration).
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con The connection to use
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return PDOStatement The executed PDOStatement object.
     * @see        BasePeer::doSelect()
     */
    public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        if (!$criteria->hasSelectClause()) {
            $criteria = clone $criteria;
            BookingVersionPeer::addSelectColumns($criteria);
        }

        // Set the correct dbName
        $criteria->setDbName(BookingVersionPeer::DATABASE_NAME);
        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseBookingVersionPeer', $criteria, $con);
        }


        // BasePeer returns a PDOStatement
        return BasePeer::doSelect($criteria, $con);
    }
    /**
     * Adds an object to the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doSelect*()
     * methods in your stub classes -- you may need to explicitly add objects
     * to the cache in order to ensure that the same objects are always returned by doSelect*()
     * and retrieveByPK*() calls.
     *
     * @param      BookingVersion $obj A BookingVersion object.
     * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
     */
    public static function addInstanceToPool($obj, $key = null)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if ($key === null) {
                $key = serialize(array((string) $obj->getId(), (string) $obj->getVersion()));
            } // if key === null
            BookingVersionPeer::$instances[$key] = $obj;
        }
    }

    /**
     * Removes an object from the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doDelete
     * methods in your stub classes -- you may need to explicitly remove objects
     * from the cache in order to prevent returning objects that no longer exist.
     *
     * @param      mixed $value A BookingVersion object or a primary key value.
     *
     * @return void
     * @throws PropelException - if the value is invalid.
     */
    public static function removeInstanceFromPool($value)
    {
        if (Propel::isInstancePoolingEnabled() && $value !== null) {
            if (is_object($value) && $value instanceof BookingVersion) {
                $key = serialize(array((string) $value->getId(), (string) $value->getVersion()));
            } elseif (is_array($value) && count($value) === 2) {
                // assume we've been passed a primary key
                $key = serialize(array((string) $value[0], (string) $value[1]));
            } else {
                $e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or BookingVersion object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
                throw $e;
            }

            unset(BookingVersionPeer::$instances[$key]);
        }
    } // removeInstanceFromPool()

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
     * @return   BookingVersion Found object or null if 1) no instance exists for specified key or 2) instance pooling has been disabled.
     * @see        getPrimaryKeyHash()
     */
    public static function getInstanceFromPool($key)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if (isset(BookingVersionPeer::$instances[$key])) {
                return BookingVersionPeer::$instances[$key];
            }
        }

        return null; // just to be explicit
    }

    /**
     * Clear the instance pool.
     *
     * @return void
     */
    public static function clearInstancePool()
    {
        BookingVersionPeer::$instances = array();
    }

    /**
     * Method to invalidate the instance pool of all tables related to booking_version
     * by a foreign key with ON DELETE CASCADE
     */
    public static function clearRelatedInstancePool()
    {
    }

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return string A string version of PK or null if the components of primary key in result array are all null.
     */
    public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
    {
        // If the PK cannot be derived from the row, return null.
        if ($row[$startcol] === null && $row[$startcol + 14] === null) {
            return null;
        }

        return serialize(array((string) $row[$startcol], (string) $row[$startcol + 14]));
    }

    /**
     * Retrieves the primary key from the DB resultset row
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, an array of the primary key columns will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return mixed The primary key of the row
     */
    public static function getPrimaryKeyFromRow($row, $startcol = 0)
    {

        return array((int) $row[$startcol], (int) $row[$startcol + 14]);
    }

    /**
     * The returned array will contain objects of the default type or
     * objects that inherit from the default.
     *
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function populateObjects(PDOStatement $stmt)
    {
        $results = array();

        // set the class once to avoid overhead in the loop
        $cls = BookingVersionPeer::getOMClass();
        // populate the object(s)
        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key = BookingVersionPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj = BookingVersionPeer::getInstanceFromPool($key))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj->hydrate($row, 0, true); // rehydrate
                $results[] = $obj;
            } else {
                $obj = new $cls();
                $obj->hydrate($row);
                $results[] = $obj;
                BookingVersionPeer::addInstanceToPool($obj, $key);
            } // if key exists
        }
        $stmt->closeCursor();

        return $results;
    }
    /**
     * Populates an object of the default type or an object that inherit from the default.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return array (BookingVersion object, last column rank)
     */
    public static function populateObject($row, $startcol = 0)
    {
        $key = BookingVersionPeer::getPrimaryKeyHashFromRow($row, $startcol);
        if (null !== ($obj = BookingVersionPeer::getInstanceFromPool($key))) {
            // We no longer rehydrate the object, since this can cause data loss.
            // See http://www.propelorm.org/ticket/509
            // $obj->hydrate($row, $startcol, true); // rehydrate
            $col = $startcol + BookingVersionPeer::NUM_HYDRATE_COLUMNS;
        } else {
            $cls = BookingVersionPeer::OM_CLASS;
            $obj = new $cls();
            $col = $obj->hydrate($row, $startcol);
            BookingVersionPeer::addInstanceToPool($obj, $key);
        }

        return array($obj, $col);
    }


    /**
     * Returns the number of rows matching criteria, joining the related Booking table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinBooking(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(BookingVersionPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            BookingVersionPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(BookingVersionPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(BookingVersionPeer::ID, BookingPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseBookingVersionPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Selects a collection of BookingVersion objects pre-filled with their Booking objects.
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of BookingVersion objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinBooking(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(BookingVersionPeer::DATABASE_NAME);
        }

        BookingVersionPeer::addSelectColumns($criteria);
        $startcol = BookingVersionPeer::NUM_HYDRATE_COLUMNS;
        BookingPeer::addSelectColumns($criteria);

        $criteria->addJoin(BookingVersionPeer::ID, BookingPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseBookingVersionPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = BookingVersionPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = BookingVersionPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {

                $cls = BookingVersionPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                BookingVersionPeer::addInstanceToPool($obj1, $key1);
            } // if $obj1 already loaded

            $key2 = BookingPeer::getPrimaryKeyHashFromRow($row, $startcol);
            if ($key2 !== null) {
                $obj2 = BookingPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = BookingPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol);
                    BookingPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 already loaded

                // Add the $obj1 (BookingVersion) to $obj2 (Booking)
                $obj2->addBookingVersion($obj1);

            } // if joined row was not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Returns the number of rows matching criteria, joining all related tables
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(BookingVersionPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            BookingVersionPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(BookingVersionPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(BookingVersionPeer::ID, BookingPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseBookingVersionPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }

    /**
     * Selects a collection of BookingVersion objects pre-filled with all related objects.
     *
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of BookingVersion objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(BookingVersionPeer::DATABASE_NAME);
        }

        BookingVersionPeer::addSelectColumns($criteria);
        $startcol2 = BookingVersionPeer::NUM_HYDRATE_COLUMNS;

        BookingPeer::addSelectColumns($criteria);
        $startcol3 = $startcol2 + BookingPeer::NUM_HYDRATE_COLUMNS;

        $criteria->addJoin(BookingVersionPeer::ID, BookingPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseBookingVersionPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = BookingVersionPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = BookingVersionPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {
                $cls = BookingVersionPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                BookingVersionPeer::addInstanceToPool($obj1, $key1);
            } // if obj1 already loaded

            // Add objects for joined Booking rows

            $key2 = BookingPeer::getPrimaryKeyHashFromRow($row, $startcol2);
            if ($key2 !== null) {
                $obj2 = BookingPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = BookingPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol2);
                    BookingPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 loaded

                // Add the $obj1 (BookingVersion) to the collection in $obj2 (Booking)
                $obj2->addBookingVersion($obj1);
            } // if joined row not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }

    /**
     * Returns the TableMap related to this peer.
     * This method is not needed for general use but a specific application could have a need.
     * @return TableMap
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function getTableMap()
    {
        return Propel::getDatabaseMap(BookingVersionPeer::DATABASE_NAME)->getTable(BookingVersionPeer::TABLE_NAME);
    }

    /**
     * Add a TableMap instance to the database for this peer class.
     */
    public static function buildTableMap()
    {
      $dbMap = Propel::getDatabaseMap(BaseBookingVersionPeer::DATABASE_NAME);
      if (!$dbMap->hasTable(BaseBookingVersionPeer::TABLE_NAME)) {
        $dbMap->addTableObject(new BookingVersionTableMap());
      }
    }

    /**
     * The class that the Peer will make instances of.
     *
     *
     * @return string ClassName
     */
    public static function getOMClass()
    {
        return BookingVersionPeer::OM_CLASS;
    }

    /**
     * Performs an INSERT on the database, given a BookingVersion or Criteria object.
     *
     * @param      mixed $values Criteria or BookingVersion object containing data that is used to create the INSERT statement.
     * @param      PropelPDO $con the PropelPDO connection to use
     * @return mixed           The new primary key.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doInsert($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity
        } else {
            $criteria = $values->buildCriteria(); // build Criteria from BookingVersion object
        }


        // Set the correct dbName
        $criteria->setDbName(BookingVersionPeer::DATABASE_NAME);

        try {
            // use transaction because $criteria could contain info
            // for more than one table (I guess, conceivably)
            $con->beginTransaction();
            $pk = BasePeer::doInsert($criteria, $con);
            $con->commit();
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }

        return $pk;
    }

    /**
     * Performs an UPDATE on the database, given a BookingVersion or Criteria object.
     *
     * @param      mixed $values Criteria or BookingVersion object containing data that is used to create the UPDATE statement.
     * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doUpdate($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $selectCriteria = new Criteria(BookingVersionPeer::DATABASE_NAME);

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity

            $comparison = $criteria->getComparison(BookingVersionPeer::ID);
            $value = $criteria->remove(BookingVersionPeer::ID);
            if ($value) {
                $selectCriteria->add(BookingVersionPeer::ID, $value, $comparison);
            } else {
                $selectCriteria->setPrimaryTableName(BookingVersionPeer::TABLE_NAME);
            }

            $comparison = $criteria->getComparison(BookingVersionPeer::VERSION);
            $value = $criteria->remove(BookingVersionPeer::VERSION);
            if ($value) {
                $selectCriteria->add(BookingVersionPeer::VERSION, $value, $comparison);
            } else {
                $selectCriteria->setPrimaryTableName(BookingVersionPeer::TABLE_NAME);
            }

        } else { // $values is BookingVersion object
            $criteria = $values->buildCriteria(); // gets full criteria
            $selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
        }

        // set the correct dbName
        $criteria->setDbName(BookingVersionPeer::DATABASE_NAME);

        return BasePeer::doUpdate($selectCriteria, $criteria, $con);
    }

    /**
     * Deletes all rows from the booking_version table.
     *
     * @param      PropelPDO $con the connection to use
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException
     */
    public static function doDeleteAll(PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }
        $affectedRows = 0; // initialize var to track total num of affected rows
        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();
            $affectedRows += BasePeer::doDeleteAll(BookingVersionPeer::TABLE_NAME, $con, BookingVersionPeer::DATABASE_NAME);
            // Because this db requires some delete cascade/set null emulation, we have to
            // clear the cached instance *after* the emulation has happened (since
            // instances get re-added by the select statement contained therein).
            BookingVersionPeer::clearInstancePool();
            BookingVersionPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs a DELETE on the database, given a BookingVersion or Criteria object OR a primary key value.
     *
     * @param      mixed $values Criteria or BookingVersion object or primary key or array of primary keys
     *              which is used to create the DELETE statement
     * @param      PropelPDO $con the connection to use
     * @return int The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
     *				if supported by native driver or if emulated using Propel.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
     public static function doDelete($values, PropelPDO $con = null)
     {
        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            // invalidate the cache for all objects of this type, since we have no
            // way of knowing (without running a query) what objects should be invalidated
            // from the cache based on this Criteria.
            BookingVersionPeer::clearInstancePool();
            // rename for clarity
            $criteria = clone $values;
        } elseif ($values instanceof BookingVersion) { // it's a model object
            // invalidate the cache for this single object
            BookingVersionPeer::removeInstanceFromPool($values);
            // create criteria based on pk values
            $criteria = $values->buildPkeyCriteria();
        } else { // it's a primary key, or an array of pks
            $criteria = new Criteria(BookingVersionPeer::DATABASE_NAME);
            // primary key is composite; we therefore, expect
            // the primary key passed to be an array of pkey values
            if (count($values) == count($values, COUNT_RECURSIVE)) {
                // array is not multi-dimensional
                $values = array($values);
            }
            foreach ($values as $value) {
                $criterion = $criteria->getNewCriterion(BookingVersionPeer::ID, $value[0]);
                $criterion->addAnd($criteria->getNewCriterion(BookingVersionPeer::VERSION, $value[1]));
                $criteria->addOr($criterion);
                // we can invalidate the cache for this single PK
                BookingVersionPeer::removeInstanceFromPool($value);
            }
        }

        // Set the correct dbName
        $criteria->setDbName(BookingVersionPeer::DATABASE_NAME);

        $affectedRows = 0; // initialize var to track total num of affected rows

        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();

            $affectedRows += BasePeer::doDelete($criteria, $con);
            BookingVersionPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Validates all modified columns of given BookingVersion object.
     * If parameter $columns is either a single column name or an array of column names
     * than only those columns are validated.
     *
     * NOTICE: This does not apply to primary or foreign keys for now.
     *
     * @param      BookingVersion $obj The object to validate.
     * @param      mixed $cols Column name or array of column names.
     *
     * @return mixed TRUE if all columns are valid or the error message of the first invalid column.
     */
    public static function doValidate($obj, $cols = null)
    {
        $columns = array();

        if ($cols) {
            $dbMap = Propel::getDatabaseMap(BookingVersionPeer::DATABASE_NAME);
            $tableMap = $dbMap->getTable(BookingVersionPeer::TABLE_NAME);

            if (! is_array($cols)) {
                $cols = array($cols);
            }

            foreach ($cols as $colName) {
                if ($tableMap->hasColumn($colName)) {
                    $get = 'get' . $tableMap->getColumn($colName)->getPhpName();
                    $columns[$colName] = $obj->$get();
                }
            }
        } else {

        }

        return BasePeer::doValidate(BookingVersionPeer::DATABASE_NAME, BookingVersionPeer::TABLE_NAME, $columns);
    }

    /**
     * Retrieve object using using composite pkey values.
     * @param   int $id
     * @param   int $version
     * @param      PropelPDO $con
     * @return   BookingVersion
     */
    public static function retrieveByPK($id, $version, PropelPDO $con = null) {
        $_instancePoolKey = serialize(array((string) $id, (string) $version));
         if (null !== ($obj = BookingVersionPeer::getInstanceFromPool($_instancePoolKey))) {
             return $obj;
        }

        if ($con === null) {
            $con = Propel::getConnection(BookingVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $criteria = new Criteria(BookingVersionPeer::DATABASE_NAME);
        $criteria->add(BookingVersionPeer::ID, $id);
        $criteria->add(BookingVersionPeer::VERSION, $version);
        $v = BookingVersionPeer::doSelect($criteria, $con);

        return !empty($v) ? $v[0] : null;
    }
    // symfony behavior

    /**
     * Returns an array of arrays that contain columns in each unique index.
     *
     * @return array
     */
    static public function getUniqueColumnNames()
    {
      return array();
    }

    // symfony_behaviors behavior

    /**
     * Returns the name of the hook to call from inside the supplied method.
     *
     * @param string $method The calling method
     *
     * @return string A hook name for {@link sfMixer}
     *
     * @throws LogicException If the method name is not recognized
     */
    static private function getMixerPreSelectHook($method)
    {
      if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
      {
        return sprintf('BaseBookingVersionPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
      }

      throw new LogicException(sprintf('Unrecognized function "%s"', $method));
    }

} // BaseBookingVersionPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseBookingVersionPeer::buildTableMap();

