<?php


/**
 * Base class that represents a query for the 'arrival_version' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue 13 May 2014 04:36:07 PM CEST
 *
 * @method ArrivalVersionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method ArrivalVersionQuery orderByBookingId($order = Criteria::ASC) Order by the booking_id column
 * @method ArrivalVersionQuery orderByDay($order = Criteria::ASC) Order by the day column
 * @method ArrivalVersionQuery orderByHour($order = Criteria::ASC) Order by the hour column
 * @method ArrivalVersionQuery orderByFlight($order = Criteria::ASC) Order by the flight column
 * @method ArrivalVersionQuery orderByRateCost($order = Criteria::ASC) Order by the rate_cost column
 * @method ArrivalVersionQuery orderByCalculatedCost($order = Criteria::ASC) Order by the calculated_cost column
 * @method ArrivalVersionQuery orderByRateName($order = Criteria::ASC) Order by the rate_name column
 * @method ArrivalVersionQuery orderByNote($order = Criteria::ASC) Order by the note column
 * @method ArrivalVersionQuery orderByPaymentMethodId($order = Criteria::ASC) Order by the payment_method_id column
 * @method ArrivalVersionQuery orderByLocalityFrom($order = Criteria::ASC) Order by the locality_from column
 * @method ArrivalVersionQuery orderByLocalityTo($order = Criteria::ASC) Order by the locality_to column
 * @method ArrivalVersionQuery orderByDriverId($order = Criteria::ASC) Order by the driver_id column
 * @method ArrivalVersionQuery orderByVehicleId($order = Criteria::ASC) Order by the vehicle_id column
 * @method ArrivalVersionQuery orderByCancelled($order = Criteria::ASC) Order by the cancelled column
 * @method ArrivalVersionQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method ArrivalVersionQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method ArrivalVersionQuery orderByVersion($order = Criteria::ASC) Order by the version column
 * @method ArrivalVersionQuery orderByVersionCreatedAt($order = Criteria::ASC) Order by the version_created_at column
 * @method ArrivalVersionQuery orderByVersionCreatedBy($order = Criteria::ASC) Order by the version_created_by column
 * @method ArrivalVersionQuery orderByBookingIdVersion($order = Criteria::ASC) Order by the booking_id_version column
 *
 * @method ArrivalVersionQuery groupById() Group by the id column
 * @method ArrivalVersionQuery groupByBookingId() Group by the booking_id column
 * @method ArrivalVersionQuery groupByDay() Group by the day column
 * @method ArrivalVersionQuery groupByHour() Group by the hour column
 * @method ArrivalVersionQuery groupByFlight() Group by the flight column
 * @method ArrivalVersionQuery groupByRateCost() Group by the rate_cost column
 * @method ArrivalVersionQuery groupByCalculatedCost() Group by the calculated_cost column
 * @method ArrivalVersionQuery groupByRateName() Group by the rate_name column
 * @method ArrivalVersionQuery groupByNote() Group by the note column
 * @method ArrivalVersionQuery groupByPaymentMethodId() Group by the payment_method_id column
 * @method ArrivalVersionQuery groupByLocalityFrom() Group by the locality_from column
 * @method ArrivalVersionQuery groupByLocalityTo() Group by the locality_to column
 * @method ArrivalVersionQuery groupByDriverId() Group by the driver_id column
 * @method ArrivalVersionQuery groupByVehicleId() Group by the vehicle_id column
 * @method ArrivalVersionQuery groupByCancelled() Group by the cancelled column
 * @method ArrivalVersionQuery groupByCreatedAt() Group by the created_at column
 * @method ArrivalVersionQuery groupByUpdatedAt() Group by the updated_at column
 * @method ArrivalVersionQuery groupByVersion() Group by the version column
 * @method ArrivalVersionQuery groupByVersionCreatedAt() Group by the version_created_at column
 * @method ArrivalVersionQuery groupByVersionCreatedBy() Group by the version_created_by column
 * @method ArrivalVersionQuery groupByBookingIdVersion() Group by the booking_id_version column
 *
 * @method ArrivalVersionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method ArrivalVersionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method ArrivalVersionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method ArrivalVersionQuery leftJoinArrival($relationAlias = null) Adds a LEFT JOIN clause to the query using the Arrival relation
 * @method ArrivalVersionQuery rightJoinArrival($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Arrival relation
 * @method ArrivalVersionQuery innerJoinArrival($relationAlias = null) Adds a INNER JOIN clause to the query using the Arrival relation
 *
 * @method ArrivalVersion findOne(PropelPDO $con = null) Return the first ArrivalVersion matching the query
 * @method ArrivalVersion findOneOrCreate(PropelPDO $con = null) Return the first ArrivalVersion matching the query, or a new ArrivalVersion object populated from the query conditions when no match is found
 *
 * @method ArrivalVersion findOneById(int $id) Return the first ArrivalVersion filtered by the id column
 * @method ArrivalVersion findOneByBookingId(int $booking_id) Return the first ArrivalVersion filtered by the booking_id column
 * @method ArrivalVersion findOneByDay(string $day) Return the first ArrivalVersion filtered by the day column
 * @method ArrivalVersion findOneByHour(string $hour) Return the first ArrivalVersion filtered by the hour column
 * @method ArrivalVersion findOneByFlight(string $flight) Return the first ArrivalVersion filtered by the flight column
 * @method ArrivalVersion findOneByRateCost(string $rate_cost) Return the first ArrivalVersion filtered by the rate_cost column
 * @method ArrivalVersion findOneByCalculatedCost(string $calculated_cost) Return the first ArrivalVersion filtered by the calculated_cost column
 * @method ArrivalVersion findOneByRateName(string $rate_name) Return the first ArrivalVersion filtered by the rate_name column
 * @method ArrivalVersion findOneByNote(string $note) Return the first ArrivalVersion filtered by the note column
 * @method ArrivalVersion findOneByPaymentMethodId(int $payment_method_id) Return the first ArrivalVersion filtered by the payment_method_id column
 * @method ArrivalVersion findOneByLocalityFrom(int $locality_from) Return the first ArrivalVersion filtered by the locality_from column
 * @method ArrivalVersion findOneByLocalityTo(int $locality_to) Return the first ArrivalVersion filtered by the locality_to column
 * @method ArrivalVersion findOneByDriverId(int $driver_id) Return the first ArrivalVersion filtered by the driver_id column
 * @method ArrivalVersion findOneByVehicleId(int $vehicle_id) Return the first ArrivalVersion filtered by the vehicle_id column
 * @method ArrivalVersion findOneByCancelled(boolean $cancelled) Return the first ArrivalVersion filtered by the cancelled column
 * @method ArrivalVersion findOneByCreatedAt(string $created_at) Return the first ArrivalVersion filtered by the created_at column
 * @method ArrivalVersion findOneByUpdatedAt(string $updated_at) Return the first ArrivalVersion filtered by the updated_at column
 * @method ArrivalVersion findOneByVersion(int $version) Return the first ArrivalVersion filtered by the version column
 * @method ArrivalVersion findOneByVersionCreatedAt(string $version_created_at) Return the first ArrivalVersion filtered by the version_created_at column
 * @method ArrivalVersion findOneByVersionCreatedBy(string $version_created_by) Return the first ArrivalVersion filtered by the version_created_by column
 * @method ArrivalVersion findOneByBookingIdVersion(int $booking_id_version) Return the first ArrivalVersion filtered by the booking_id_version column
 *
 * @method array findById(int $id) Return ArrivalVersion objects filtered by the id column
 * @method array findByBookingId(int $booking_id) Return ArrivalVersion objects filtered by the booking_id column
 * @method array findByDay(string $day) Return ArrivalVersion objects filtered by the day column
 * @method array findByHour(string $hour) Return ArrivalVersion objects filtered by the hour column
 * @method array findByFlight(string $flight) Return ArrivalVersion objects filtered by the flight column
 * @method array findByRateCost(string $rate_cost) Return ArrivalVersion objects filtered by the rate_cost column
 * @method array findByCalculatedCost(string $calculated_cost) Return ArrivalVersion objects filtered by the calculated_cost column
 * @method array findByRateName(string $rate_name) Return ArrivalVersion objects filtered by the rate_name column
 * @method array findByNote(string $note) Return ArrivalVersion objects filtered by the note column
 * @method array findByPaymentMethodId(int $payment_method_id) Return ArrivalVersion objects filtered by the payment_method_id column
 * @method array findByLocalityFrom(int $locality_from) Return ArrivalVersion objects filtered by the locality_from column
 * @method array findByLocalityTo(int $locality_to) Return ArrivalVersion objects filtered by the locality_to column
 * @method array findByDriverId(int $driver_id) Return ArrivalVersion objects filtered by the driver_id column
 * @method array findByVehicleId(int $vehicle_id) Return ArrivalVersion objects filtered by the vehicle_id column
 * @method array findByCancelled(boolean $cancelled) Return ArrivalVersion objects filtered by the cancelled column
 * @method array findByCreatedAt(string $created_at) Return ArrivalVersion objects filtered by the created_at column
 * @method array findByUpdatedAt(string $updated_at) Return ArrivalVersion objects filtered by the updated_at column
 * @method array findByVersion(int $version) Return ArrivalVersion objects filtered by the version column
 * @method array findByVersionCreatedAt(string $version_created_at) Return ArrivalVersion objects filtered by the version_created_at column
 * @method array findByVersionCreatedBy(string $version_created_by) Return ArrivalVersion objects filtered by the version_created_by column
 * @method array findByBookingIdVersion(int $booking_id_version) Return ArrivalVersion objects filtered by the booking_id_version column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseArrivalVersionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseArrivalVersionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'ArrivalVersion', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new ArrivalVersionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     ArrivalVersionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return ArrivalVersionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof ArrivalVersionQuery) {
            return $criteria;
        }
        $query = new ArrivalVersionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj = $c->findPk(array(12, 34), $con);
     * </code>
     *
     * @param array $key Primary key to use for the query
                         A Primary key composition: [$id, $version]
     * @param     PropelPDO $con an optional connection object
     *
     * @return   ArrivalVersion|ArrivalVersion[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = ArrivalVersionPeer::getInstanceFromPool(serialize(array((string) $key[0], (string) $key[1]))))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(ArrivalVersionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   ArrivalVersion A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `BOOKING_ID`, `DAY`, `HOUR`, `FLIGHT`, `RATE_COST`, `CALCULATED_COST`, `RATE_NAME`, `NOTE`, `PAYMENT_METHOD_ID`, `LOCALITY_FROM`, `LOCALITY_TO`, `DRIVER_ID`, `VEHICLE_ID`, `CANCELLED`, `CREATED_AT`, `UPDATED_AT`, `VERSION`, `VERSION_CREATED_AT`, `VERSION_CREATED_BY`, `BOOKING_ID_VERSION` FROM `arrival_version` WHERE `ID` = :p0 AND `VERSION` = :p1';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key[0], PDO::PARAM_INT);
            $stmt->bindValue(':p1', $key[1], PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new ArrivalVersion();
            $obj->hydrate($row);
            ArrivalVersionPeer::addInstanceToPool($obj, serialize(array((string) $key[0], (string) $key[1])));
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return ArrivalVersion|ArrivalVersion[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(array(12, 56), array(832, 123), array(123, 456)), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|ArrivalVersion[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {
        $this->addUsingAlias(ArrivalVersionPeer::ID, $key[0], Criteria::EQUAL);
        $this->addUsingAlias(ArrivalVersionPeer::VERSION, $key[1], Criteria::EQUAL);

        return $this;
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {
        if (empty($keys)) {
            return $this->add(null, '1<>1', Criteria::CUSTOM);
        }
        foreach ($keys as $key) {
            $cton0 = $this->getNewCriterion(ArrivalVersionPeer::ID, $key[0], Criteria::EQUAL);
            $cton1 = $this->getNewCriterion(ArrivalVersionPeer::VERSION, $key[1], Criteria::EQUAL);
            $cton0->addAnd($cton1);
            $this->addOr($cton0);
        }

        return $this;
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @see       filterByArrival()
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(ArrivalVersionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the booking_id column
     *
     * Example usage:
     * <code>
     * $query->filterByBookingId(1234); // WHERE booking_id = 1234
     * $query->filterByBookingId(array(12, 34)); // WHERE booking_id IN (12, 34)
     * $query->filterByBookingId(array('min' => 12)); // WHERE booking_id > 12
     * </code>
     *
     * @param     mixed $bookingId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByBookingId($bookingId = null, $comparison = null)
    {
        if (is_array($bookingId)) {
            $useMinMax = false;
            if (isset($bookingId['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::BOOKING_ID, $bookingId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($bookingId['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::BOOKING_ID, $bookingId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::BOOKING_ID, $bookingId, $comparison);
    }

    /**
     * Filter the query on the day column
     *
     * Example usage:
     * <code>
     * $query->filterByDay('2011-03-14'); // WHERE day = '2011-03-14'
     * $query->filterByDay('now'); // WHERE day = '2011-03-14'
     * $query->filterByDay(array('max' => 'yesterday')); // WHERE day > '2011-03-13'
     * </code>
     *
     * @param     mixed $day The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByDay($day = null, $comparison = null)
    {
        if (is_array($day)) {
            $useMinMax = false;
            if (isset($day['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::DAY, $day['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($day['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::DAY, $day['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::DAY, $day, $comparison);
    }

    /**
     * Filter the query on the hour column
     *
     * Example usage:
     * <code>
     * $query->filterByHour('2011-03-14'); // WHERE hour = '2011-03-14'
     * $query->filterByHour('now'); // WHERE hour = '2011-03-14'
     * $query->filterByHour(array('max' => 'yesterday')); // WHERE hour > '2011-03-13'
     * </code>
     *
     * @param     mixed $hour The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByHour($hour = null, $comparison = null)
    {
        if (is_array($hour)) {
            $useMinMax = false;
            if (isset($hour['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::HOUR, $hour['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($hour['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::HOUR, $hour['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::HOUR, $hour, $comparison);
    }

    /**
     * Filter the query on the flight column
     *
     * Example usage:
     * <code>
     * $query->filterByFlight('fooValue');   // WHERE flight = 'fooValue'
     * $query->filterByFlight('%fooValue%'); // WHERE flight LIKE '%fooValue%'
     * </code>
     *
     * @param     string $flight The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByFlight($flight = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($flight)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $flight)) {
                $flight = str_replace('*', '%', $flight);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::FLIGHT, $flight, $comparison);
    }

    /**
     * Filter the query on the rate_cost column
     *
     * Example usage:
     * <code>
     * $query->filterByRateCost(1234); // WHERE rate_cost = 1234
     * $query->filterByRateCost(array(12, 34)); // WHERE rate_cost IN (12, 34)
     * $query->filterByRateCost(array('min' => 12)); // WHERE rate_cost > 12
     * </code>
     *
     * @param     mixed $rateCost The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByRateCost($rateCost = null, $comparison = null)
    {
        if (is_array($rateCost)) {
            $useMinMax = false;
            if (isset($rateCost['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::RATE_COST, $rateCost['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($rateCost['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::RATE_COST, $rateCost['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::RATE_COST, $rateCost, $comparison);
    }

    /**
     * Filter the query on the calculated_cost column
     *
     * Example usage:
     * <code>
     * $query->filterByCalculatedCost(1234); // WHERE calculated_cost = 1234
     * $query->filterByCalculatedCost(array(12, 34)); // WHERE calculated_cost IN (12, 34)
     * $query->filterByCalculatedCost(array('min' => 12)); // WHERE calculated_cost > 12
     * </code>
     *
     * @param     mixed $calculatedCost The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByCalculatedCost($calculatedCost = null, $comparison = null)
    {
        if (is_array($calculatedCost)) {
            $useMinMax = false;
            if (isset($calculatedCost['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::CALCULATED_COST, $calculatedCost['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($calculatedCost['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::CALCULATED_COST, $calculatedCost['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::CALCULATED_COST, $calculatedCost, $comparison);
    }

    /**
     * Filter the query on the rate_name column
     *
     * Example usage:
     * <code>
     * $query->filterByRateName('fooValue');   // WHERE rate_name = 'fooValue'
     * $query->filterByRateName('%fooValue%'); // WHERE rate_name LIKE '%fooValue%'
     * </code>
     *
     * @param     string $rateName The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByRateName($rateName = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($rateName)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $rateName)) {
                $rateName = str_replace('*', '%', $rateName);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::RATE_NAME, $rateName, $comparison);
    }

    /**
     * Filter the query on the note column
     *
     * Example usage:
     * <code>
     * $query->filterByNote('fooValue');   // WHERE note = 'fooValue'
     * $query->filterByNote('%fooValue%'); // WHERE note LIKE '%fooValue%'
     * </code>
     *
     * @param     string $note The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByNote($note = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($note)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $note)) {
                $note = str_replace('*', '%', $note);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::NOTE, $note, $comparison);
    }

    /**
     * Filter the query on the payment_method_id column
     *
     * Example usage:
     * <code>
     * $query->filterByPaymentMethodId(1234); // WHERE payment_method_id = 1234
     * $query->filterByPaymentMethodId(array(12, 34)); // WHERE payment_method_id IN (12, 34)
     * $query->filterByPaymentMethodId(array('min' => 12)); // WHERE payment_method_id > 12
     * </code>
     *
     * @param     mixed $paymentMethodId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByPaymentMethodId($paymentMethodId = null, $comparison = null)
    {
        if (is_array($paymentMethodId)) {
            $useMinMax = false;
            if (isset($paymentMethodId['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::PAYMENT_METHOD_ID, $paymentMethodId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($paymentMethodId['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::PAYMENT_METHOD_ID, $paymentMethodId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::PAYMENT_METHOD_ID, $paymentMethodId, $comparison);
    }

    /**
     * Filter the query on the locality_from column
     *
     * Example usage:
     * <code>
     * $query->filterByLocalityFrom(1234); // WHERE locality_from = 1234
     * $query->filterByLocalityFrom(array(12, 34)); // WHERE locality_from IN (12, 34)
     * $query->filterByLocalityFrom(array('min' => 12)); // WHERE locality_from > 12
     * </code>
     *
     * @param     mixed $localityFrom The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByLocalityFrom($localityFrom = null, $comparison = null)
    {
        if (is_array($localityFrom)) {
            $useMinMax = false;
            if (isset($localityFrom['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::LOCALITY_FROM, $localityFrom['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($localityFrom['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::LOCALITY_FROM, $localityFrom['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::LOCALITY_FROM, $localityFrom, $comparison);
    }

    /**
     * Filter the query on the locality_to column
     *
     * Example usage:
     * <code>
     * $query->filterByLocalityTo(1234); // WHERE locality_to = 1234
     * $query->filterByLocalityTo(array(12, 34)); // WHERE locality_to IN (12, 34)
     * $query->filterByLocalityTo(array('min' => 12)); // WHERE locality_to > 12
     * </code>
     *
     * @param     mixed $localityTo The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByLocalityTo($localityTo = null, $comparison = null)
    {
        if (is_array($localityTo)) {
            $useMinMax = false;
            if (isset($localityTo['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::LOCALITY_TO, $localityTo['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($localityTo['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::LOCALITY_TO, $localityTo['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::LOCALITY_TO, $localityTo, $comparison);
    }

    /**
     * Filter the query on the driver_id column
     *
     * Example usage:
     * <code>
     * $query->filterByDriverId(1234); // WHERE driver_id = 1234
     * $query->filterByDriverId(array(12, 34)); // WHERE driver_id IN (12, 34)
     * $query->filterByDriverId(array('min' => 12)); // WHERE driver_id > 12
     * </code>
     *
     * @param     mixed $driverId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByDriverId($driverId = null, $comparison = null)
    {
        if (is_array($driverId)) {
            $useMinMax = false;
            if (isset($driverId['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::DRIVER_ID, $driverId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($driverId['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::DRIVER_ID, $driverId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::DRIVER_ID, $driverId, $comparison);
    }

    /**
     * Filter the query on the vehicle_id column
     *
     * Example usage:
     * <code>
     * $query->filterByVehicleId(1234); // WHERE vehicle_id = 1234
     * $query->filterByVehicleId(array(12, 34)); // WHERE vehicle_id IN (12, 34)
     * $query->filterByVehicleId(array('min' => 12)); // WHERE vehicle_id > 12
     * </code>
     *
     * @param     mixed $vehicleId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByVehicleId($vehicleId = null, $comparison = null)
    {
        if (is_array($vehicleId)) {
            $useMinMax = false;
            if (isset($vehicleId['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::VEHICLE_ID, $vehicleId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($vehicleId['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::VEHICLE_ID, $vehicleId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::VEHICLE_ID, $vehicleId, $comparison);
    }

    /**
     * Filter the query on the cancelled column
     *
     * Example usage:
     * <code>
     * $query->filterByCancelled(true); // WHERE cancelled = true
     * $query->filterByCancelled('yes'); // WHERE cancelled = true
     * </code>
     *
     * @param     boolean|string $cancelled The value to use as filter.
     *              Non-boolean arguments are converted using the following rules:
     *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByCancelled($cancelled = null, $comparison = null)
    {
        if (is_string($cancelled)) {
            $cancelled = in_array(strtolower($cancelled), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
        }

        return $this->addUsingAlias(ArrivalVersionPeer::CANCELLED, $cancelled, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query on the version column
     *
     * Example usage:
     * <code>
     * $query->filterByVersion(1234); // WHERE version = 1234
     * $query->filterByVersion(array(12, 34)); // WHERE version IN (12, 34)
     * $query->filterByVersion(array('min' => 12)); // WHERE version > 12
     * </code>
     *
     * @param     mixed $version The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByVersion($version = null, $comparison = null)
    {
        if (is_array($version) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(ArrivalVersionPeer::VERSION, $version, $comparison);
    }

    /**
     * Filter the query on the version_created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByVersionCreatedAt('2011-03-14'); // WHERE version_created_at = '2011-03-14'
     * $query->filterByVersionCreatedAt('now'); // WHERE version_created_at = '2011-03-14'
     * $query->filterByVersionCreatedAt(array('max' => 'yesterday')); // WHERE version_created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $versionCreatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByVersionCreatedAt($versionCreatedAt = null, $comparison = null)
    {
        if (is_array($versionCreatedAt)) {
            $useMinMax = false;
            if (isset($versionCreatedAt['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::VERSION_CREATED_AT, $versionCreatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($versionCreatedAt['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::VERSION_CREATED_AT, $versionCreatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::VERSION_CREATED_AT, $versionCreatedAt, $comparison);
    }

    /**
     * Filter the query on the version_created_by column
     *
     * Example usage:
     * <code>
     * $query->filterByVersionCreatedBy('fooValue');   // WHERE version_created_by = 'fooValue'
     * $query->filterByVersionCreatedBy('%fooValue%'); // WHERE version_created_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $versionCreatedBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByVersionCreatedBy($versionCreatedBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($versionCreatedBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $versionCreatedBy)) {
                $versionCreatedBy = str_replace('*', '%', $versionCreatedBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::VERSION_CREATED_BY, $versionCreatedBy, $comparison);
    }

    /**
     * Filter the query on the booking_id_version column
     *
     * Example usage:
     * <code>
     * $query->filterByBookingIdVersion(1234); // WHERE booking_id_version = 1234
     * $query->filterByBookingIdVersion(array(12, 34)); // WHERE booking_id_version IN (12, 34)
     * $query->filterByBookingIdVersion(array('min' => 12)); // WHERE booking_id_version > 12
     * </code>
     *
     * @param     mixed $bookingIdVersion The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function filterByBookingIdVersion($bookingIdVersion = null, $comparison = null)
    {
        if (is_array($bookingIdVersion)) {
            $useMinMax = false;
            if (isset($bookingIdVersion['min'])) {
                $this->addUsingAlias(ArrivalVersionPeer::BOOKING_ID_VERSION, $bookingIdVersion['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($bookingIdVersion['max'])) {
                $this->addUsingAlias(ArrivalVersionPeer::BOOKING_ID_VERSION, $bookingIdVersion['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArrivalVersionPeer::BOOKING_ID_VERSION, $bookingIdVersion, $comparison);
    }

    /**
     * Filter the query by a related Arrival object
     *
     * @param   Arrival|PropelObjectCollection $arrival The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   ArrivalVersionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByArrival($arrival, $comparison = null)
    {
        if ($arrival instanceof Arrival) {
            return $this
                ->addUsingAlias(ArrivalVersionPeer::ID, $arrival->getId(), $comparison);
        } elseif ($arrival instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ArrivalVersionPeer::ID, $arrival->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByArrival() only accepts arguments of type Arrival or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Arrival relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function joinArrival($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Arrival');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Arrival');
        }

        return $this;
    }

    /**
     * Use the Arrival relation Arrival object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   ArrivalQuery A secondary query class using the current class as primary query
     */
    public function useArrivalQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinArrival($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Arrival', 'ArrivalQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   ArrivalVersion $arrivalVersion Object to remove from the list of results
     *
     * @return ArrivalVersionQuery The current query, for fluid interface
     */
    public function prune($arrivalVersion = null)
    {
        if ($arrivalVersion) {
            $this->addCond('pruneCond0', $this->getAliasedColName(ArrivalVersionPeer::ID), $arrivalVersion->getId(), Criteria::NOT_EQUAL);
            $this->addCond('pruneCond1', $this->getAliasedColName(ArrivalVersionPeer::VERSION), $arrivalVersion->getVersion(), Criteria::NOT_EQUAL);
            $this->combine(array('pruneCond0', 'pruneCond1'), Criteria::LOGICAL_OR);
        }

        return $this;
    }

}
