<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tl_tasks' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Jul 29 18:55:03 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfTaskLoggerPlugin.lib.model
 */
class tlTaskQuery extends BasetlTaskQuery
{
}
