<?php



/**
 * Skeleton subclass for performing query and update operations on the 'airport' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Apr 27 17:36:34 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class AirportPeer extends BaseAirportPeer
{

    public static function PopulateAirports(){
      ProjectConfiguration::registerComposer();
      $api_key = sfConfig::get('app_sita_airport_api_key',"");
      $uri = 'https://airport.api.aero/airport?user_key='.$api_key;
      $response = Httpful\Request::get($uri)->send();
      $body = $response->body;
      $body = substr(substr($body,9),0,-1);
      $body = json_decode($body);

      foreach($body->airports as $airport ){
          $apt = new Airport();
          $apt->setCode($airport->code);
          $apt->setName($airport->name);
          $apt->setCity($airport->city);
          $apt->setCountry($airport->country);
          $apt->setLat($airport->lat);
          $apt->setLng($airport->lng);
          $apt->setTimezone($airport->timezone);
          $apt->save();
      }
    }


}
