<?php



/**
 * Skeleton subclass for performing query and update operations on the 'airport' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Apr 27 17:36:34 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class AirportQuery extends BaseAirportQuery
{
}
