<?php



/**
 * Skeleton subclass for performing query and update operations on the 'area' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Wed Oct 22 12:29:31 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class AreaPeer extends BaseAreaPeer
{

    public static function doSelectPager($page=1, $item_per_page = 10, Criteria $criteria = null)
    {
        if ($criteria === null)
        {
            $criteria = new Criteria();
        }
        $pager = new sfPropelPager('Area', $item_per_page);
        $pager->setCriteria($criteria);
        $pager->setPage($page);
        $pager->setPeerMethod('doSelect');
        $pager->init();
        return $pager;
    }
}
