<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_user_profile' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Wed Apr 16 21:58:08 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class customerQuery extends BasecustomerQuery
{
}
