<?php



/**
 * Skeleton subclass for representing a row from the 'vehicle_type' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Wed 09 Apr 2014 02:54:23 PM CEST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class VehicleType extends BaseVehicleType
{
    public function __toString(){
        return $this->getName();
    }

    public function preInsert(PropelPDO $con = null)
    {
        $this->setName(strtoupper($this->getName()));
        return true;
    }

    public function preUpdate(PropelPDO $con = null)
    {
        $this->setName(strtoupper($this->getName()));
        return true;
    }
}
