propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  company:
    _propel_behaviors:
      Timestampable:         ~
    id:                      ~
    name:                    { type: varchar(100), required: true }
    vat_number:              { type: varchar(20),  required: true }
    phone:                   { type: varchar(20),  required: false }
    fax:                     { type: varchar(20),  required: false }
    mobile:                  { type: varchar(20),  required: false }
    email:                   { type: varchar(100), required: false }
    site:                    { type: varchar(150), required: false }
    formatted_address:       { type: varchar(150), required: false }
    lat:                     { type: DECIMAL, size: 18, scale: 2, required: false }
    lon:                     { type: DECIMAL, size: 18, scale: 2, required: false }

  vehicle_type:
    _propel_behaviors:
      Timestampable:         ~
    id:                      ~
    name:                    { type: varchar(100), required: true, unique: true }

  vehicle:
    _propel_behaviors:
      Timestampable:         ~
    id:                      ~
    vehicle_type_id:         { type: integer, foreignTable: vehicle_type, foreignReference: id, required: true, onDelete: cascade }
    model :                  { type: varchar(100), required: true }
    plate_number:            { type: varchar(20) }
    frame_number:            { type: varchar(50) }
    mileage:                 { type: bigint }
    note:                    { type: varchar(255) }

  sf_guard_user_profile:
    _attributes: { phpName: sfGuardUserProfile }
    id:
    user_id:     { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    first_name:  varchar(20)
    last_name:   varchar(20)
