<?php
/**
 * Created by PhpStorm.
 * User: poldotz
 * Date: 22/04/14
 * Time: 10.53
 */


class CustomerEmailValidatorSchema extends sfValidatorSchema {


    protected function configure($options = array(), $messages = array())
    {
        parent::configure($options, $messages); // TODO: Change the autogenerated stub
    }

    protected function doClean($values)
    {
        $errorSchema = new sfValidatorErrorSchema($this);

        if(isset($values) && strlen($values)){
            $user = sfGuardUserPeer::retrieveByUsernameOrEmail($values);

            if(isset($user)){
                $errorSchema->addError(new sfValidatorError($this, 'Campo Email usato precedentemente da un altro utente.'), 'email');
                throw new sfValidatorErrorSchema($this, $errorSchema);
            }
        }

        return $values;
    }
}